sudo: required

arch:
  packages:
    - gcc
    - qt5-base
    - qt5-declarative
    - qt5-multimedia
    - qt5-svg
    - qt5-tools
    - qt5-webkit
  script:
    - "qmake"
    - "make"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
