sudo: required
dist: trusty

language:
- cpp

env:
  global:
  - secure: "OmCtURVfcw98Szm/USLmM2/piWs+QcNZjUhQzJnfPGkTSRGHPtCgJBlTSK1wI5c/apJJpXwh0O3+Tif5Sy3a05Tt8/DGSb++Knq/OCq2PMO+bgQtnPBPlCVOCJzjaFnQGMgwB7sWgG1Y/Tm6SUfv7OylQ0tpSXrolk3If7hfpC5WNFbSyu5HQDyfFcgf5st4T7pA58t5Ol8kGpyYzs7aWNxZqELsGrdC7p0ueAHGZGejQ2joMP8fwwxYpQfcFW+bVOZVJD2YO/vTPlLI10/URND7eenvmf6Az4286R0fXzdtOGrr2fAltLYoX2tyE9Wq+NG7La3PO5KdX1NgLUq+Q5niH6LOL6Ipddbd0lDOCxxs43231h0SMUqsDRLEZYe3OhyHfmJRntTx5Q2Lu4FHBruUjdGKwHhNZHNOs8G57u+2dMKFX1RMrV2En20IJGU0AKkaP8JB1grFTEvUk8vj3g/j8OxEpgzWH/cGZLopbtVnMi3vWSniVRLMK57Htqs0ELc1UPnlJmENfZR8+4JWeTxjgBVD2pNPy6BR80+N6ZoBqIZyNhkDiy4ZxSFznAgg0JiDcJQrfD4owPByt4ee+5eZp6J/RsZN20Ns8VFOAxOpaawI805F1Gp8xB0x+2WF9+RJyMoibvTIoZxAT7xBD7W8i4EdT0GzodnkAg6WxdQ="

addons:
  coverity_scan:
    project:
      name: "madnight/chessx"
      description: "Build submitted via Travis CI"
    notification_email: mail@beuke.org
    build_command_prepend: qmake
    build_command: make -j 4
    branch_pattern: coverity_scan

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev qt5-default qttools5-dev-tools qtmultimedia5-dev libqt5svg5*

script:
- qmake
- make

