sudo: required
dist: trusty

language:
  - cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev qt5-default qttools5-dev-tools qtmultimedia5-dev libqt5svg5*

script:
 - qmake
 - make
